apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-capstone
  labels:
    app: echo-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-capstone
  template:
    metadata:
      labels:
        app: echo-capstone
    spec:
      containers:
        - name: echo-capstone
          image: echo-capstone:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
