apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-capstone.fullname" . }}
  labels: {{- include "echo-capstone.labels" . | nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector: {{- include "echo-capstone.selectorLabels" . | nindent 8 }}
