/**
 * Maestro Banquets - Components Barrel File
 * 
 * Centralized exports for all components including
 * panels, UI components, and utilities.
 */

// Panel Components
export * from './panels';
export { default as panels } from './panels';

// UI Components (from ui directory)
// Note: Individual UI components should be imported directly from ./ui/
// as they are auto-generated by shadcn and have their own structure

// Builder.io Components
export * from '../builder/maestro-banquets.builder-seed';
export { default as BanquetsWorkspace } from '../builder/maestro-banquets.builder-seed';
