version: "3.9"
services:
  echo-capstone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENTRY: ${BUILD_ENTRY:-src/index.jsx}
    image: echo-capstone:latest
    container_name: echo-capstone
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "${APP_PORT:-8080}:80"
    depends_on: []
    restart: unless-stopped
